### ISSUE TITLE
About Me Template

### ISSUE THREAD

**Issue by stringerjazz** [bellydrum/discord-project#8]
Here's a rough idea of what I was thinking for each of our "About Me" sections:

Could we possibly replace header with a game screen cap of that person's choice?  I don't know how easy this is to do but I think it could be kinda cool.
Also as far as our pictures go, I think we should go with both professional headshots and stylized caricatures.  I have a good idea of how I think this could look, but can better explain my idea for it next time we have a meeting in person.

- **Name**: Stringer
- **Role(s)**: Lead Creative, Discord Administrator
- **Favorite Nintendo Series**: _The Legend of Zelda_
- **Favorite Non-tendo Game**: _Sly 2: Band of Thieves_
- **Ideal Pokémon Team** (Use sprites from Bulbapedia): Arcanine, Espeon, Zapdos, Vileplume, Blastoise, Tyranitar
- **Favorite Personal Switch Clip** (Hosted on The Superfam YouTube channel)
- **Social Media/Stream/Soundcloud/Whatever Links**

**Comment by bellydrum** [comment]
This is good stuff. These will go on the Member object (what our database considers a "member").

So far our Member object looks like this:

Member
- lastname
- firstname
- username
- birthday
- role
- favorite_nintendo_series
- favorite_non_nintendo_series
- pokemon_team
- social_media

**Comment by bellydrum** [comment]
Closing this because /about/member.html is built out with the above features. It's now ready for suggestions and updates moving forward as separate issues
